name: run-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./test
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Test
        run: docker-compose run tests
